/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodosRouteImport } from './routes/todos'
import { Route as FinishedRouteImport } from './routes/finished'

const TodosRoute = TodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const FinishedRoute = FinishedRouteImport.update({
  id: '/finished',
  path: '/finished',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/finished': typeof FinishedRoute
  '/todos': typeof TodosRoute
}
export interface FileRoutesByTo {
  '/finished': typeof FinishedRoute
  '/todos': typeof TodosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/finished': typeof FinishedRoute
  '/todos': typeof TodosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/finished' | '/todos'
  fileRoutesByTo: FileRoutesByTo
  to: '/finished' | '/todos'
  id: '__root__' | '/finished' | '/todos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  FinishedRoute: typeof FinishedRoute
  TodosRoute: typeof TodosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/todos': {
      id: '/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof TodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finished': {
      id: '/finished'
      path: '/finished'
      fullPath: '/finished'
      preLoaderRoute: typeof FinishedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  FinishedRoute: FinishedRoute,
  TodosRoute: TodosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
