/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodosRouteImport } from './routes/todos'
import { Route as FinishedRouteImport } from './routes/finished'
import { Route as GroupsIndexRouteImport } from './routes/groups/index'
import { Route as GroupsGroupIDRouteImport } from './routes/groups/$groupID'

const TodosRoute = TodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const FinishedRoute = FinishedRouteImport.update({
  id: '/finished',
  path: '/finished',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsIndexRoute = GroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIDRoute = GroupsGroupIDRouteImport.update({
  id: '/groups/$groupID',
  path: '/groups/$groupID',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/finished': typeof FinishedRoute
  '/todos': typeof TodosRoute
  '/groups/$groupID': typeof GroupsGroupIDRoute
  '/groups': typeof GroupsIndexRoute
}
export interface FileRoutesByTo {
  '/finished': typeof FinishedRoute
  '/todos': typeof TodosRoute
  '/groups/$groupID': typeof GroupsGroupIDRoute
  '/groups': typeof GroupsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/finished': typeof FinishedRoute
  '/todos': typeof TodosRoute
  '/groups/$groupID': typeof GroupsGroupIDRoute
  '/groups/': typeof GroupsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/finished' | '/todos' | '/groups/$groupID' | '/groups'
  fileRoutesByTo: FileRoutesByTo
  to: '/finished' | '/todos' | '/groups/$groupID' | '/groups'
  id: '__root__' | '/finished' | '/todos' | '/groups/$groupID' | '/groups/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  FinishedRoute: typeof FinishedRoute
  TodosRoute: typeof TodosRoute
  GroupsGroupIDRoute: typeof GroupsGroupIDRoute
  GroupsIndexRoute: typeof GroupsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/todos': {
      id: '/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof TodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finished': {
      id: '/finished'
      path: '/finished'
      fullPath: '/finished'
      preLoaderRoute: typeof FinishedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/': {
      id: '/groups/'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupID': {
      id: '/groups/$groupID'
      path: '/groups/$groupID'
      fullPath: '/groups/$groupID'
      preLoaderRoute: typeof GroupsGroupIDRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  FinishedRoute: FinishedRoute,
  TodosRoute: TodosRoute,
  GroupsGroupIDRoute: GroupsGroupIDRoute,
  GroupsIndexRoute: GroupsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
